/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteMyCustomerArgs } from "./DeleteMyCustomerArgs";
import { MyCustomerFindManyArgs } from "./MyCustomerFindManyArgs";
import { MyCustomerFindUniqueArgs } from "./MyCustomerFindUniqueArgs";
import { MyCustomer } from "./MyCustomer";
import { MyCustomerService } from "../myCustomer.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => MyCustomer)
export class MyCustomerResolverBase {
  constructor(
    protected readonly service: MyCustomerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MyCustomer",
    action: "read",
    possession: "any",
  })
  async _myCustomersMeta(
    @graphql.Args() args: MyCustomerFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [MyCustomer])
  @nestAccessControl.UseRoles({
    resource: "MyCustomer",
    action: "read",
    possession: "any",
  })
  async myCustomers(
    @graphql.Args() args: MyCustomerFindManyArgs
  ): Promise<MyCustomer[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => MyCustomer, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MyCustomer",
    action: "read",
    possession: "own",
  })
  async myCustomer(
    @graphql.Args() args: MyCustomerFindUniqueArgs
  ): Promise<MyCustomer | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MyCustomer)
  @nestAccessControl.UseRoles({
    resource: "MyCustomer",
    action: "delete",
    possession: "any",
  })
  async deleteMyCustomer(
    @graphql.Args() args: DeleteMyCustomerArgs
  ): Promise<MyCustomer | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
